# Generated by Django 3.2.3 on 2021-10-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210524_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_items',
            field=models.IntegerField(default=0, verbose_name='sold_items'),
        ),
    ]
